# 1.	Write a Python Program to Add Two Matrices?

In [5]:
from numpy import  *

In [10]:
matrix1 = array([[18,20,22,17],[11,18,21,18],
   [15,21,20,19]])

In [11]:
matrix2=array([[11,20,22,21],
   [18,17,23,22],[12,22,20,18]])

In [14]:
print(matrix1.shape)
print(matrix2.shape)

(3, 4)
(3, 4)


In [15]:
matrix=matrix1+matrix2

In [16]:
matrix

array([[29, 40, 44, 38],
       [29, 35, 44, 40],
       [27, 43, 40, 37]])

Another Method

In [17]:
matrix1

array([[18, 20, 22, 17],
       [11, 18, 21, 18],
       [15, 21, 20, 19]])

In [18]:
matrix2

array([[11, 20, 22, 21],
       [18, 17, 23, 22],
       [12, 22, 20, 18]])

In [23]:
result=array([[0,0,0,0],
   [0,0,0,0],[0,0,0,0]])

In [27]:
for i in range(len(matrix1)):
    for j in range (len(matrix1[0])):
        result[i][j]=matrix1[i][j]+matrix2[i][j]

In [28]:
result

array([[29, 40, 44, 38],
       [29, 35, 44, 40],
       [27, 43, 40, 37]])

# 2.	Write a Python Program to Multiply Two Matrices?

In [29]:
matrix1

array([[18, 20, 22, 17],
       [11, 18, 21, 18],
       [15, 21, 20, 19]])

In [30]:
matrix2

array([[11, 20, 22, 21],
       [18, 17, 23, 22],
       [12, 22, 20, 18]])

In [31]:
result=array([[0,0,0,0],
   [0,0,0,0],[0,0,0,0]])

In [32]:
for i in range(len(matrix1)):
    for j in range (len(matrix1[0])):
        result[i][j]=matrix1[i][j]*matrix2[i][j]

In [33]:
result

array([[198, 400, 484, 357],
       [198, 306, 483, 396],
       [180, 462, 400, 342]])

Another Method

In [36]:
matrix1*matrix2

array([[198, 400, 484, 357],
       [198, 306, 483, 396],
       [180, 462, 400, 342]])

# 3.	Write a Python Program to Transpose a Matrix?

In [37]:
matrix1

array([[18, 20, 22, 17],
       [11, 18, 21, 18],
       [15, 21, 20, 19]])

In [47]:
r=matrix1.shape[0]
c=matrix1.shape[1]

In [48]:
print("row=",r,"col=",c)

row= 3 col= 4


In [59]:
result=array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])

In [60]:
for i in range(0,3):
    for j in range(0,4):
        result[j,i]=matrix1[i,j]

In [61]:
#Transpose of matrix1
result


array([[18, 11, 15],
       [20, 18, 21],
       [22, 21, 20],
       [17, 18, 19]])

# Write a Python Program to Sort Words in Alphabetic Order?

In [87]:
# Program to sort alphabetically the words form a string provided by the user

my_str = "The proposal to acquire the MQ9B long-endurance drones, armed with air-to-ground missiles, is likely to be cleared by the Defence Acquisition Council  in the next few weeks following which it will be placed before the PM led Cabinet Committee on Security, they said."

# To take input from the user
#my_str = input("Enter a string: ")

# breakdown the string into a list of words
words = [word.lower() for word in my_str.split()]

# sort the list
words.sort()

# display the sorted words

print("The sorted words are:")
for word in words:
    print(word)


The sorted words are:
acquire
acquisition
air-to-ground
armed
be
be
before
by
cabinet
cleared
committee
council
defence
drones,
few
following
in
is
it
led
likely
long-endurance
missiles,
mq9b
next
on
placed
pm
proposal
said.
security,
the
the
the
the
the
they
to
to
weeks
which
will
with


# 5.	Write a Python Program to Remove Punctuation From a String?


In [88]:
 punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''


In [100]:
#user_input=input()

user_input="Welcome???@@##$ heLLo#$% woRd %$^$%^"

In [102]:
for i in user_input.lower():
    if i in punctuations:
            user_input = user_input.replace(i, "")

print(user_input.lower())

welcome hello word 
